app/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('service.urls'))
]

app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('service.urls')),
]

service/urls.py
from django.contrib import admin
from django.urls import path

from . import views


app_name = 'service'

urlpatterns = [
    path('', views.index, name='index'),
    path('search_staff/', views.search_staff, name='search_staff'),
    path('search_company/', views.search_company, name='search_company'),
    path('search_staff/exchange', views.exchange_search_staff,
         name='search_staff/exchange'),
    path('search_company/exchange', views.exchange_search_company,
         name='search_company/exchange')
]

service/models.py
from django.db import models

# Create your models here.
from django.db.models import Q


class Sex(models.Model):
    '''性別フィールド'''
    sex = models.CharField('性別', max_length=10, unique=True)

    def __str__(self):
        return self.sex


class Requirement(models.Model):
    '''資格フィールド'''
    requirement = models.CharField('資格', max_length=50, unique=True)

    def __str__(self):
        return self.requirement


class Citizenship(models.Model):
    '''国籍フィールド'''
    citizenship = models.CharField('国籍', max_length=20, unique=True)

    def __str__(self):
        return self.citizenship


class RegisteredStaffQuerySet(models.QuerySet):
    '''クエリセットのメソッド追加'''

    def search(self, query=None):
        # クエリセットの取得
        query_set = self
        # 連絡が繋がるスタッフのみにフィルタリング
        query_set = query_set.filter(is_contact=True)

        try:
            # 性別絞り込み
            if query['sex'] != 'both':  # 性別指定がある時
                query_set = query_set.filter(sex__sex=query['sex'])

            # 年齢絞り込み
            query_set = query_set.filter(age__lte=query['age'])

            # 資格絞り込み
            query_set = query_set.filter(
                Q(requirement__requirement__exact=query['requirement']) | Q(requirement__requirement__isnull=True))

            # 希望時給絞り込み
            query_set = query_set.filter(
                Q(hourly_pay__lte=query['hourly_pay']) | Q(hourly_pay__isnull=True))

            # 国籍絞り込み
            if query['citizenship'] != 'both':  # 国籍指定がある時
                query_set = query_set.filter(
                    Q(citizenship__citizenship__exact=query['citizenship']) | Q(citizenship__citizenship__isnull=True))

            # 居住地絞り込み
            # 未実装

            # アップデート順に並び替え
            query_set = query_set.order_by('-updated_datetime')
        except:
            import traceback
            traceback.print_exc()
            query_set = None

        return query_set


class RegisteredStaffManager(models.Manager):
    '''objectsからのメソッド追加'''

    def get_queryset(self):
        return RegisteredStaffQuerySet(self.model, using=self._db)

    def search(self, query=None):
        return self.get_queryset().search(query=query)


class RegisteredStaff(models.Model):
    '''派遣スタッフフィールド'''
    name = models.CharField(
        blank=False, null=False, max_length=30, verbose_name='名前'
    )  # 名前
    sex = models.ForeignKey(
        Sex, on_delete=models.PROTECT, verbose_name='性別'
    )  # 性別
    age = models.IntegerField(
        blank=False, null=False, verbose_name='年齢'
    )  # 年齢
    requirement = models.ForeignKey(
        Requirement, on_delete=models.PROTECT, blank=True, null=True, verbose_name='資格'
    )  # 資格
    hourly_pay = models.IntegerField(
        blank=True, null=True, verbose_name='希望時給'
    )  # 希望時給
    citizenship = models.ForeignKey(
        Citizenship, on_delete=models.PROTECT, blank=True, null=True, verbose_name='国籍'
    )  # 国籍
    residence = models.CharField(
        blank=True, null=True, max_length=100, verbose_name='居住地'
    )  # 居住地
    is_contact = models.BooleanField(
        verbose_name='連絡がすぐ繋がるか'
    )  # すぐに連絡が繋がるかどうか
    created_datetime = models.DateTimeField(
        auto_now_add=True
    )  # 作成日
    updated_datetime = models.DateTimeField(
        auto_now=True
    )  # 更新日

    objects = RegisteredStaffManager()

    def __str__(self):
        return self.name


class Address(models.Model):
    '''住所フィールド'''
    zip_code = models.CharField(
        verbose_name='郵便番号', max_length=8, blank=True,
    )  # 郵便番号
    address1 = models.CharField(
        verbose_name='都道府県', max_length=40, blank=True,
    )  # 都道府県
    address2 = models.CharField(
        verbose_name='市区町村番地', max_length=40, blank=True,
    )  # 市区町村番地
    address3 = models.CharField(
        verbose_name='建物名', max_length=40, blank=True,
    )  # 建物名

    def __str__(self):
        return self.address1 + self.address2 + self.address3


class Company(models.Model):
    '''会社フィールド'''
    name = models.CharField(
        '会社名', max_length=10, unique=True
    )  # 会社名
    address = models.ForeignKey(
        Address, on_delete=models.PROTECT, verbose_name='会社住所'
    )  # 会社住所

    def __str__(self):
        return self.name


class RegisteredCompany(models.Model):
    '''求人希望情報フィールド'''
    name = models.ForeignKey(
        Company, on_delete=models.PROTECT, verbose_name='求人会社'
    )  # 求人会社名
    sex = models.ForeignKey(
        Sex, on_delete=models.PROTECT, verbose_name='性別'
    )  # 性別
    age = models.IntegerField(
        blank=False, null=False, verbose_name='年齢'
    )  # 年齢
    requirement = models.ForeignKey(
        Requirement, on_delete=models.PROTECT, blank=True, null=True, verbose_name='資格'
    )  # 資格
    hourly_pay = models.IntegerField(
        blank=True, null=True, verbose_name='希望時給'
    )  # 希望時給
    citizenship = models.ForeignKey(
        Citizenship, on_delete=models.PROTECT, blank=True, null=True, verbose_name='国籍'
    )  # 国籍
    created_datetime = models.DateTimeField(
        auto_now_add=True
    )  # 作成日
    updated_datetime = models.DateTimeField(
        auto_now=True
    )  # 更新日

    def __str__(self):
        return self.name

service/forms.py
from .models import RegisteredStaff, Sex, Requirement, Citizenship

from django import forms

# selectタグの選択肢
SEX_CHOICE = (
    ('both', 'どちらでも可'),
    ('man', '男性のみ'),
    ('woman', '女性のみ'),
)
REQUIREMENT_CHOICE = (
    ('nothing', '必要なし'),
)
RESIDENCE_CHOICE = (
    ('both', '外国人でも可'),
    ('japan', '日本人のみ'),
)


class SearchStaffForm(forms.Form):
    # formタグ作成
    sex = forms.ChoiceField(label='性別', choices=SEX_CHOICE)
    age = forms.IntegerField(label='年齢', initial=99)
    requirement = forms.ChoiceField(label='資格', choices=REQUIREMENT_CHOICE)
    hourly_pay = forms.IntegerField(label='希望時給', initial=9999)
    citizenship = forms.ChoiceField(label='国籍', choices=RESIDENCE_CHOICE)
    residence = forms.CharField(label='居住地', required=False)


class SearchCompanyForm(forms.Form):
    # formタグ作成
    sex = forms.ChoiceField(label='性別', choices=SEX_CHOICE)
    age = forms.IntegerField(label='年齢', initial=99)
    requirement = forms.ChoiceField(label='資格', choices=REQUIREMENT_CHOICE)
    hourly_pay = forms.IntegerField(label='希望時給', initial=9999)
    citizenship = forms.ChoiceField(label='国籍', choices=RESIDENCE_CHOICE)
    residence = forms.CharField(label='会社住所', required=False)

service/views.py
from django.shortcuts import render

from service.models import RegisteredStaff

# Create your views here.
from .forms import SearchStaffForm, SearchCompanyForm
from django.http.response import JsonResponse


def index(request):
    '''初期ページ'''
    return render(request, 'service/index.html')


def search_staff(request):
    '''登録スタッフ検索ページ'''
    forms = SearchStaffForm()
    return render(request, 'service/search_staff.html', {'forms': forms})


def search_company(request):
    '''登録企業検索ページ'''
    # 入力フォーム
    forms = SearchCompanyForm()
    # 順位表示用range
    for_range = [i+1 for i in range(10)]

    send_data = {
        'forms': forms,
        'for_range': for_range,
        'ranking': None,
    }
    return render(request, 'service/search_company.html', send_data)


# やり取りするデータ
# data = { 'sex':, 'age':, 'requirement':, 'hourly_pay':, 'citizenship':, 'residence': }
def exchange_search_staff(request):
    '''スタッフ検索内容のやり取り'''
    get_data = request.POST

    try:
        # 検索結果の該当者数を取得
        raw_number = search_staff_func(data=get_data).count()
    except:
        import traceback
        traceback.print_exc()
        raw_number = -1

    try:
        # 条件緩和での検索
        result = processed_stuff_search(data=get_data)
        processed1_data, processed2_data = result[0], result[1]
        processed1_number = search_staff_func(data=processed1_data).count()
        processed2_number = search_staff_func(data=processed2_data).count()

        # 緩和前のデータと等しい時
        if processed1_data == get_data:
            processed1_data, processed1_number = {}, -1
            if processed2_data == get_data:
                processed2_data, processed2_number = {}, -1
    except:
        import traceback
        traceback.print_exc()
        processed1_data, processed1_number = {}, -1
        processed2_data, processed2_number = {}, -1

    send_data = {
        'raw': {
            'data': get_data,
            'number': raw_number,
        },
        'processed1': {
            'data': processed1_data,
            'number': processed1_number,
        },
        'processed2': {
            'data': processed2_data,
            'number': processed2_number,
        },
    }

    return JsonResponse(send_data)


def processed_stuff_search(data):
    '''複数の条件緩和案を実行し、最適案を確定'''
    # try_data = [
    #     [検索内容, 検索結果数],
    #     [検索内容, ...]
    # ]
    try_data = [[data.copy(), 0] for i in range(5)]

    # 性別緩和
    if data['sex'] != 'both':  # 緩和可能な時
        # 条件内容の変更
        try_data[0][0]['sex'] = 'both'
        # 検索結果
        try_data[0][1] = search_staff_func(data=try_data[0][0]).count()

    # 年齢緩和
    if data['age'] != '99':  # 緩和可能な時
        # 条件内容の変更
        try_data[1][0]['age'] = str(int(try_data[1][0]['age']) + 10)
        # 検索結果
        try_data[1][1] = search_staff_func(data=try_data[1][0]).count()

    # 資格緩和
    if data['requirement'] != 'nothing':  # 緩和可能な時
        # 条件内容の変更
        try_data[2][0]['requirement'] = 'nothing'
        # 検索結果
        try_data[2][1] = search_staff_func(data=try_data[2][0]).count()

    # 希望時給緩和
    if data['hourly_pay'] != '9999':  # 緩和可能な時
        # 条件内容の変更
        try_data[3][0]['hourly_pay'] = str(
            int(try_data[3][0]['hourly_pay']) + 50)
        # 検索結果
        try_data[3][1] = search_staff_func(data=try_data[3][0]).count()

    # 国籍緩和
    if data['citizenship'] != 'both':  # 緩和可能な時
        # 条件内容の変更
        try_data[4][0]['citizenship'] = 'both'
        # 検索結果
        try_data[4][1] = search_staff_func(data=try_data[4][0]).count()

    # 人数の多い順にソート
    result = sorted(try_data, key=lambda x: x[1], reverse=True)

    return [result[i][0] for i in range(len(result))]


def search_staff_func(data):
    '''登録スタッフ検索'''
    data = RegisteredStaff.objects.search(query=data)
    return data


def exchange_search_company(request):
    '''会社検索内容のやり取り'''
    pass

service/templates/service/base.html
<!DOCTYPE html>
<html>

<head>
    <title>ワークナビ</title>
</head>

<body>
    {% block content %}
    {% endblock %}
</body>

</html>

service/templates/service/index.html
{% extends 'service/base.html' %}
{% block content %}
<h1 style='text-align: center;'>TOP</h1>
<div style='margin-left: 20px;'>
    <h2>1. スタッフ検索</h2>
    <!--登録スタッフを検索する-->
    <div style='text-align: center;'>
        <a href="{% url 'service:search_staff' %}">検索ページへ移動</a>
    </div>

    <h2>2. 企業検索</h2>
    <!--登録企業を検索す-->
    <div style='text-align: center;'>
        <a href="{% url 'service:search_company' %}">検索ページへ移動</a>
    </div>
</div>
{% endblock %}

service/templates/service/search_company.html
{% extends 'service/base.html' %}
{% block content %}
<h1 style='text-align: center;'>企業検索</h1>
<div style="text-align: center;">
    <a href="{% url 'service:index' %}">TOPページに戻る</a>
</div>

<h2>求人内容</h2>

<form id='search' align="center" method="post">{% csrf_token %}
    {{forms}}
    <button type="submit">検索</button>
</form>

<h2>企業優先順位</h2>
<table style="border-collapse: collapse" width="90%" id="result" border="1" align="center">
    <thead>
        <tr bgcolor="#eeeeee" align="center">
            <th width="5%">順位</th>
            <th>会社名</th>
            <th width="12%">性別</th>
            <th width="5%">年齢</th>
            <th width="15%">資格</th>
            <th width="10%">希望時給</th>
            <th width="13%">国籍</th>
            <th width="10%">希望人数</th>
        </tr>
    </thead>

    <tbody>
        {% for i in for_range %}
        <tr align="center">
            <td bgcolor="#f0f0f0">{{i}}</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        {% endfor %}
    </tbody>



</table>


{% endblock %}

service/templates/service/search_staff.html
{% extends 'service/base.html' %}
{% block content %}
<h1 style='text-align: center;'>スタッフ検索</h1>
<div style="text-align: center;">
    <a href="{% url 'service:index' %}">TOPページに戻る</a>
</div>

<h2>検索項目</h2>

<form id='search' align="center">
    {{forms}}
    <button type="submit">検索</button>
</form>

<h2>検索結果</h2>
<table style="border-collapse: collapse" width="90%" id="result" border="1" align="center">
    <tr bgcolor="#f5f5f5" align="center">
        <th width="12%">性別</th>
        <th width="5%">年齢</th>
        <th width="15%">資格</th>
        <th width="10%">希望時給</th>
        <th width="13%">国籍</th>
        <th>居住地</th>
        <th width="7%">人数</th>
    </tr>
</table>


<script>
    const searchElm = document.getElementById('search');

    function addResultToTable(addDataDict, color) {
        // テーブル取得
        var table = document.getElementById('result');
        // 行を先頭に追加
        var row = table.insertRow(1);
        // セルの挿入
        var sexCell = row.insertCell(-1);
        var ageCell = row.insertCell(-1);
        var requirementCell = row.insertCell(-1);
        var hourlyPayCell = row.insertCell(-1);
        var citizenshipCell = row.insertCell(-1);
        var residenceCell = row.insertCell(-1);
        var numberCell = row.insertCell(-1);

        row.style.background = color
        row.style.textAlign = "center"

        // sexCell.style.background = color
        // ageCell.style.background = color
        // requirementCell.style.background = color
        // hourlyPayCell.style.background = color
        // citizenshipCell.style.background = color
        // residenceCell.style.background = color
        // numberCell.style.background = color



        // セルの書き換え
        if (addDataDict.data.sex == 'both') {
            sexCell.innerHTML = 'どちらでも可'
        } else if (addDataDict.data.sex == 'man') {
            sexCell.innerHTML = '男性のみ'
        } else if (addDataDict.data.sex == 'woman') {
            sexCell.innerHTML = '女性のみ'
        } else {
            sexCell.innerHTML = 'エラー1'
        }

        ageCell.innerHTML = "~" + addDataDict.data.age

        if (addDataDict.data.requirement == 'nothing') {
            requirementCell.innerHTML = '必要なし'
        } else {
            requirementCell.innerHTML = 'エラー2'
        }

        hourlyPayCell.innerHTML = "¥ " + addDataDict.data.hourly_pay

        if (addDataDict.data.citizenship == 'both') {
            citizenshipCell.innerHTML = '外国人でも可'
        } else if (addDataDict.data.citizenship == 'japan') {
            citizenshipCell.innerHTML = '日本人のみ'
        } else {
            citizenshipCell.innerHTML = 'エラー3'
        }

        residenceCell.innerHTML = addDataDic.data.residence

        numberCell.innerHTML = addDataDic.number
    }

    searchElm.addEventListener('submit', (e) => {
        // イベントをキャンセル
        e.preventDefault();

        // formに入力されたデータの取得
        const formData = new FormData(searchElm);

        // CSRF に関する処理
        // 参考URL : https://zenn.dev/hathle/articles/django-fetch
        const getCookie = (name) => {
            if (document.cookie && document.cookie !== '') {
                for (const cookie of document.cookie.split(';')) {
                    const [key, value] = cookie.trim().split('=')
                    if (key === name) {
                        return decodeURIComponent(value)
                    }
                }
            }
        }
        const csrftoken = getCookie('csrftoken')


        const MAIN_COLOR = '#cccccc'
        const SUB_COLOR = '#e5e5e5'

        const execSearch = async () => {
            // 検索データの送受信
            const data = await fetch("/search_staff/exchange", {
                method: "POST",
                body: formData,
                headers: {
                    'X-CSRFToken': csrftoken,
                }
            })

            // 受け取ったデータをJSON形式に変換
            const result = await data.json();

            // 受け取ったデータを分ける
            const raw_data = result.raw;
            const processed1_data = result.processed1;
            const processed2_data = result.processed2;



            // DOM操作
            if (Object.keys(processed2_data.data).length != 0) {
                addResultToTable(addDataDic = processed2_data, color = SUB_COLOR)
            }

            if (Object.keys(processed1_data.data).length != 0) {
                addResultToTable(addDataDic = processed1_data, color = SUB_COLOR)
            }

            addResultToTable(addDataDic = raw_data, color = MAIN_COLOR)

        }
        execSearch();
    });
</script>




{% endblock %}